version: '3.7'

services:
  redpanda:
    image: docker.redpanda.com/vectorized/redpanda:latest
    container_name: redpanda-1
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --set redpanda.empty_seed_starts_cluster=false
      - --seeds "redpanda-1:33145"
      - --advertise-rpc-addr redpanda-1:33145 
      - --advertise-kafka-addr redpanda-1:9092
    networks:
      - redpandanet
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 9644:9644
    volumes:
      - redpanda1:/var/lib/redpanda/data

  admin_app:
    build: ./admin_app
    container_name: admin_app
    networks:
      - redpandanet
    environment:
      - HOST_BROKER=redpanda-1
      - PORT_BROKER=9092
    depends_on:
      - redpanda

  producer_app:
    build: ./producer_app
    container_name: producer_app
    networks:
      - redpandanet
    environment:
      - HOST_BROKER=redpanda-1
      - PORT_BROKER=9092
    depends_on:
      - admin_app

  consumer_producer_app:
    build: ./consumer_producer_app
    container_name: consumer_producer_app
    networks:
      - redpandanet
    environment:
      - HOST_BROKER=redpanda-1
      - PORT_BROKER=9092
    depends_on:
      - producer_app

  consumer_app:
    build: ./consumer_app
    container_name: consumer_app
    networks:
      - redpandanet
    environment:
      - HOST_BROKER=redpanda-1
      - PORT_BROKER=9092
    depends_on:
      - consumer_producer_app

networks:
  redpandanet:
    name: redpandanet

volumes:
  redpanda1:
    name: redpanda1